### ISSUE TITLE
Seenbot writes to stdout

### ISSUE THREAD

**Issue by JAChapmanII** [Nolshine/SeenBot#5]
`Seenbot` should not `print` directly to stdout. The primary reason _I_ care is because everything written to stdout is interpreted by `jitro` and possibly sent to IRC. 

Beyond that, libraries should not really print anywhere. Whether `Seenbot` is a lib, or just a utility in this program is up for debate, but at the very least printing debug info to stderr is the way to go.

An alternative for printing to stderr in `Seenbot` would be to accept a `logger` object, and call `.write` on that if something happens worth knowing about -- but that's a little convoluted just for debugging. If it uses the same interface as `sys.stderr`, it would remain possible to just pass `sys.stderr` as the `logger`, though.

**Comment by Nolshine** [comment]
Fixed; see branch `processor_rewrite.`
