### ISSUE TITLE
Use umiki instead of pastebin

### ISSUE THREAD

**Issue by JAChapmanII** [Nolshine/SeenBot#6]
My shoddy paste functionality is now live!

example: https://serv2.pink/api/umiki/v1/q3XjfjCt89bifU0UrEEedStNHk4kcpjm

(actually that should expire in roughly an hour...)

Number one thing to remember is, always use https!

You make a `POST` request against `https://serv2.pink/api/umiki/v1`. In the body, you include `api_key` (message me on IRC and I'll send you yours), and the `content`. Expiration cannot currently be set, but is set at 1 hour from creation currently.

Basically it works like this:

```
[jac@rasa ~]$ curl -XPOST -d 'api_key={your api key}&content=test Solshine' 'https://serv2.pink/api/umiki/v1'
{ 'err': 0, 'msg': 'success', 'url': 'https://serv2.pink/api/umiki/v1/q3XjfjCt89bifU0UrEEedStNHk4kcpjm' }
```

If the `api_key` is not correct:

```
[jac@rasa ~]$ curl -XPOST -d 'api_key=bad&content=test Solshine' 'https://serv2.pink/api/umiki/v1'
{ 'err': -1, 'msg': 'api_key not found' }
```

If the `api_key` is not given at all (it's similar if you leave off `content`):

```
[jac@rasa ~]$ curl -XPOST -d 'content=test Solshine' 'https://serv2.pink/api/umiki/v1'
{ 'err': -3, 'msg': 'parameter required', 'parameter': 'api_key' }
```

Now I need to create actual documentation...

**Comment by Nolshine** [comment]
updated to use your pb - see: `processor_rewrite` branch
